### ISSUE TITLE
make sure HTML indents and line breaks are consistent

### ISSUE THREAD

**Issue by greglinch** [jessdilla23/Homepage#2]
The indents should match the hierarchy of the page. Some things to fix indents:

https://github.com/jessdilla23/Homepage/blob/master/Homepage.html#L7-L9
https://github.com/jessdilla23/Homepage/blob/master/Homepage.html#L17

These had double indents and extra lines in between:

https://github.com/jessdilla23/Homepage/blob/master/Homepage.html#L22-L28

This should be indented under the h3:

https://github.com/jessdilla23/Homepage/blob/master/Homepage.html#L22-L28

This indent doesn't have the same number of spaces as the others:

https://github.com/jessdilla23/Homepage/blob/master/Homepage.html#L22-L28

Everything should be indented one level within HTML to start (as you did with `<head>`) and finish:

https://github.com/jessdilla23/Homepage/blob/master/Homepage.html#L22-L28

**Comment by jessdilla23** [comment]
I have cleaned up spaces, but I'm not sure if I got the indenting right.
