### ISSUE TITLE
fix broken image link

### ISSUE THREAD

**Issue by greglinch** [jessdilla23/Homepage#3]
Any images either need to be in the repository or linked to a live URL. This one is still located on your computer, so I was unable to see it:

https://github.com/jessdilla23/Homepage/blob/master/Homepage.html#L22-L28

![screen shot 2018-09-04 at 9 29 44 pm](https://user-images.githubusercontent.com/327783/45065894-b21c3000-b089-11e8-8e94-574bd40384ad.png)

**Comment by jessdilla23** [comment]
Photo added to repo & link updated.
